apiVersion: "etcd.database.coreos.com/v1alpha1"
kind: "EtcdBackup"
metadata:
  name: example-etcd-cluster
spec:
  clusterName: example-etcd-cluster
  storageType: s3
  backupIntervalInSecond: 30
  s3:
    s3Bucket: jenkins-etcd-operator
    prefix: prefix
    awsSecret: aws